### PR TITLE
String operations

### PR DESCRIPTION
**Pull request by jazhten**

### CODE REVIEW

**Comment by jazhten** [comment]
Also abstracted String related commands to StringOperations class

**Comment by jazhten** [comment]
Sorry don't merge yet, there's some bug with one of the commands

**Comment by jazhten** [comment]
Just to explain the new convention for edit commands :

- If numSeason increases:
        - set a new array for episodes and init the new seasons with 1 episode

- if numSeasons decreases:
        - replace episodes with smaller sized array and delete the episodes in the later seasons
        - initially episodes=[10,12] for 2 seasons, when resized to 1, episodes=[10]

**Comment by judowha** [comment]
> Just to explain the new changes for edit commands :
> 
> getRawEpisodesForSeasons() used instead of getEpisodesForSeasons() -> this one checks array using season-1 so it'll lead to bounds errors
> 
> * If numSeason increases:
>   - set a new array for episodes and init the new seasons with 1 episode
> * if numSeasons decreases:
>   - replace episodes with smaller sized array and delete the episodes in the later seasons
>   - initially episodes=[10,12] for 2 seasons, when resized to 1, episodes=[10]

Understand! But we need to ensure that users give a valid input. e.g. they change the number of seasons to 0. If we assume the user input is perfect, then it will work well.

**Review by shikai-zhou — APPROVED** [review]
thanks jazhten

**Pull request merged**
